spring:
  main:
    lazy-initialization: true
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

mybatis-plus:
  lazy-initialization: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  jwt:
    secret: ${JWT_SECRET:}
  wechat:
    app-id: ${WECHAT_APP_ID:}
    app-secret: ${WECHAT_APP_SECRET:}
    mock-enabled: false
